jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'
server:
  port: 8482

spring:
  
  datasource:
    url: jdbc:mysql://localhost:3306/bugdb?serverTimezone=UTC

    password: 12345
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
